// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mysteriumnetwork/iqp/enterprise (interfaces: EnterpriseBlockchain)

// Package mocks is a generated GoMock package.
package mocks

import (
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "github.com/golang/mock/gomock"
	eip155 "github.com/mysteriumnetwork/iqp/blockchain/eip155"
)

// MockEnterpriseBlockchain is a mock of EnterpriseBlockchain interface.
type MockEnterpriseBlockchain struct {
	ctrl     *gomock.Controller
	recorder *MockEnterpriseBlockchainMockRecorder
}

// MockEnterpriseBlockchainMockRecorder is the mock recorder for MockEnterpriseBlockchain.
type MockEnterpriseBlockchainMockRecorder struct {
	mock *MockEnterpriseBlockchain
}

// NewMockEnterpriseBlockchain creates a new mock instance.
func NewMockEnterpriseBlockchain(ctrl *gomock.Controller) *MockEnterpriseBlockchain {
	mock := &MockEnterpriseBlockchain{ctrl: ctrl}
	mock.recorder = &MockEnterpriseBlockchainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnterpriseBlockchain) EXPECT() *MockEnterpriseBlockchainMockRecorder {
	return m.recorder
}

// AddLiquidity mocks base method.
func (m *MockEnterpriseBlockchain) AddLiquidity(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLiquidity", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLiquidity indicates an expected call of AddLiquidity.
func (mr *MockEnterpriseBlockchainMockRecorder) AddLiquidity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLiquidity", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).AddLiquidity), arg0, arg1)
}

// ApproveLiquidityTokensToEnterprise mocks base method.
func (m *MockEnterpriseBlockchain) ApproveLiquidityTokensToEnterprise(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveLiquidityTokensToEnterprise", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveLiquidityTokensToEnterprise indicates an expected call of ApproveLiquidityTokensToEnterprise.
func (mr *MockEnterpriseBlockchainMockRecorder) ApproveLiquidityTokensToEnterprise(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveLiquidityTokensToEnterprise", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).ApproveLiquidityTokensToEnterprise), arg0, arg1)
}

// ApproveLiquidityTokensToService mocks base method.
func (m *MockEnterpriseBlockchain) ApproveLiquidityTokensToService(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveLiquidityTokensToService", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveLiquidityTokensToService indicates an expected call of ApproveLiquidityTokensToService.
func (mr *MockEnterpriseBlockchainMockRecorder) ApproveLiquidityTokensToService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveLiquidityTokensToService", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).ApproveLiquidityTokensToService), arg0, arg1)
}

// Borrow mocks base method.
func (m *MockEnterpriseBlockchain) Borrow(arg0, arg1, arg2 common.Address, arg3, arg4 *big.Int, arg5 uint32) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Borrow", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Borrow indicates an expected call of Borrow.
func (mr *MockEnterpriseBlockchainMockRecorder) Borrow(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Borrow", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).Borrow), arg0, arg1, arg2, arg3, arg4, arg5)
}

// DecreaseLiquidity mocks base method.
func (m *MockEnterpriseBlockchain) DecreaseLiquidity(arg0 common.Address, arg1, arg2 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseLiquidity", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseLiquidity indicates an expected call of DecreaseLiquidity.
func (mr *MockEnterpriseBlockchainMockRecorder) DecreaseLiquidity(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseLiquidity", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).DecreaseLiquidity), arg0, arg1, arg2)
}

// EstimateLoan mocks base method.
func (m *MockEnterpriseBlockchain) EstimateLoan(arg0, arg1, arg2 common.Address, arg3 *big.Int, arg4 uint32) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateLoan", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateLoan indicates an expected call of EstimateLoan.
func (mr *MockEnterpriseBlockchainMockRecorder) EstimateLoan(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateLoan", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).EstimateLoan), arg0, arg1, arg2, arg3, arg4)
}

// EstimateLoanDetailed mocks base method.
func (m *MockEnterpriseBlockchain) EstimateLoanDetailed(arg0, arg1 common.Address, arg2 *big.Int, arg3 uint32) (eip155.LoanEstimateDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateLoanDetailed", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(eip155.LoanEstimateDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateLoanDetailed indicates an expected call of EstimateLoanDetailed.
func (mr *MockEnterpriseBlockchainMockRecorder) EstimateLoanDetailed(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateLoanDetailed", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).EstimateLoanDetailed), arg0, arg1, arg2, arg3)
}

// GetAccountState mocks base method.
func (m *MockEnterpriseBlockchain) GetAccountState(arg0, arg1 common.Address) (eip155.AccountState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountState", arg0, arg1)
	ret0, _ := ret[0].(eip155.AccountState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountState indicates an expected call of GetAccountState.
func (mr *MockEnterpriseBlockchainMockRecorder) GetAccountState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountState", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetAccountState), arg0, arg1)
}

// GetAccruedInterest mocks base method.
func (m *MockEnterpriseBlockchain) GetAccruedInterest(arg0 common.Address, arg1 *big.Int) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccruedInterest", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccruedInterest indicates an expected call of GetAccruedInterest.
func (mr *MockEnterpriseBlockchainMockRecorder) GetAccruedInterest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccruedInterest", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetAccruedInterest), arg0, arg1)
}

// GetAllowsPerpetual mocks base method.
func (m *MockEnterpriseBlockchain) GetAllowsPerpetual(arg0 common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowsPerpetual", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowsPerpetual indicates an expected call of GetAllowsPerpetual.
func (mr *MockEnterpriseBlockchainMockRecorder) GetAllowsPerpetual(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowsPerpetual", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetAllowsPerpetual), arg0)
}

// GetAvailableReserve mocks base method.
func (m *MockEnterpriseBlockchain) GetAvailableReserve(arg0 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableReserve", arg0)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableReserve indicates an expected call of GetAvailableReserve.
func (mr *MockEnterpriseBlockchainMockRecorder) GetAvailableReserve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableReserve", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetAvailableReserve), arg0)
}

// GetBaseRate mocks base method.
func (m *MockEnterpriseBlockchain) GetBaseRate(arg0 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseRate", arg0)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseRate indicates an expected call of GetBaseRate.
func (mr *MockEnterpriseBlockchainMockRecorder) GetBaseRate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseRate", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetBaseRate), arg0)
}

// GetBaseTokenAddress mocks base method.
func (m *MockEnterpriseBlockchain) GetBaseTokenAddress(arg0 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseTokenAddress", arg0)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseTokenAddress indicates an expected call of GetBaseTokenAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) GetBaseTokenAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseTokenAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetBaseTokenAddress), arg0)
}

// GetBaseUri mocks base method.
func (m *MockEnterpriseBlockchain) GetBaseUri(arg0 common.Address) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseUri", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseUri indicates an expected call of GetBaseUri.
func (mr *MockEnterpriseBlockchainMockRecorder) GetBaseUri(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseUri", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetBaseUri), arg0)
}

// GetBondingCurve mocks base method.
func (m *MockEnterpriseBlockchain) GetBondingCurve(arg0 common.Address) (eip155.BondingCurve, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBondingCurve", arg0)
	ret0, _ := ret[0].(eip155.BondingCurve)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBondingCurve indicates an expected call of GetBondingCurve.
func (mr *MockEnterpriseBlockchainMockRecorder) GetBondingCurve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBondingCurve", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetBondingCurve), arg0)
}

// GetBorrowTokenIds mocks base method.
func (m *MockEnterpriseBlockchain) GetBorrowTokenIds(arg0, arg1 common.Address) ([]*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowTokenIds", arg0, arg1)
	ret0, _ := ret[0].([]*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowTokenIds indicates an expected call of GetBorrowTokenIds.
func (mr *MockEnterpriseBlockchainMockRecorder) GetBorrowTokenIds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowTokenIds", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetBorrowTokenIds), arg0, arg1)
}

// GetBorrowerLoanReturnGracePeriod mocks base method.
func (m *MockEnterpriseBlockchain) GetBorrowerLoanReturnGracePeriod(arg0 common.Address) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowerLoanReturnGracePeriod", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowerLoanReturnGracePeriod indicates an expected call of GetBorrowerLoanReturnGracePeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) GetBorrowerLoanReturnGracePeriod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowerLoanReturnGracePeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetBorrowerLoanReturnGracePeriod), arg0)
}

// GetChainID mocks base method.
func (m *MockEnterpriseBlockchain) GetChainID() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainID")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainID indicates an expected call of GetChainID.
func (mr *MockEnterpriseBlockchainMockRecorder) GetChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainID", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetChainID))
}

// GetConverterAddress mocks base method.
func (m *MockEnterpriseBlockchain) GetConverterAddress(arg0 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConverterAddress", arg0)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConverterAddress indicates an expected call of GetConverterAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) GetConverterAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConverterAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetConverterAddress), arg0)
}

// GetEnergyAt mocks base method.
func (m *MockEnterpriseBlockchain) GetEnergyAt(arg0, arg1 common.Address, arg2 uint32) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnergyAt", arg0, arg1, arg2)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnergyAt indicates an expected call of GetEnergyAt.
func (mr *MockEnterpriseBlockchainMockRecorder) GetEnergyAt(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnergyAt", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetEnergyAt), arg0, arg1, arg2)
}

// GetEnterpriseCollectorAddress mocks base method.
func (m *MockEnterpriseBlockchain) GetEnterpriseCollectorAddress(arg0 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseCollectorAddress", arg0)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseCollectorAddress indicates an expected call of GetEnterpriseCollectorAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) GetEnterpriseCollectorAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseCollectorAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetEnterpriseCollectorAddress), arg0)
}

// GetEnterpriseInfo mocks base method.
func (m *MockEnterpriseBlockchain) GetEnterpriseInfo(arg0 common.Address) (eip155.EnterpriseInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseInfo", arg0)
	ret0, _ := ret[0].(eip155.EnterpriseInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseInfo indicates an expected call of GetEnterpriseInfo.
func (mr *MockEnterpriseBlockchainMockRecorder) GetEnterpriseInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseInfo", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetEnterpriseInfo), arg0)
}

// GetEnterpriseLoanCollectGracePeriod mocks base method.
func (m *MockEnterpriseBlockchain) GetEnterpriseLoanCollectGracePeriod(arg0 common.Address) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseLoanCollectGracePeriod", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseLoanCollectGracePeriod indicates an expected call of GetEnterpriseLoanCollectGracePeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) GetEnterpriseLoanCollectGracePeriod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseLoanCollectGracePeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetEnterpriseLoanCollectGracePeriod), arg0)
}

// GetEnterpriseVaultAddress mocks base method.
func (m *MockEnterpriseBlockchain) GetEnterpriseVaultAddress(arg0 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseVaultAddress", arg0)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseVaultAddress indicates an expected call of GetEnterpriseVaultAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) GetEnterpriseVaultAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseVaultAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetEnterpriseVaultAddress), arg0)
}

// GetGCFeePercent mocks base method.
func (m *MockEnterpriseBlockchain) GetGCFeePercent(arg0 common.Address) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCFeePercent", arg0)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGCFeePercent indicates an expected call of GetGCFeePercent.
func (mr *MockEnterpriseBlockchainMockRecorder) GetGCFeePercent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCFeePercent", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetGCFeePercent), arg0)
}

// GetGapHalvingPeriod mocks base method.
func (m *MockEnterpriseBlockchain) GetGapHalvingPeriod(arg0 common.Address) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGapHalvingPeriod", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGapHalvingPeriod indicates an expected call of GetGapHalvingPeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) GetGapHalvingPeriod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGapHalvingPeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetGapHalvingPeriod), arg0)
}

// GetInterestGapHalvingPeriod mocks base method.
func (m *MockEnterpriseBlockchain) GetInterestGapHalvingPeriod(arg0 common.Address) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterestGapHalvingPeriod", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterestGapHalvingPeriod indicates an expected call of GetInterestGapHalvingPeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) GetInterestGapHalvingPeriod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterestGapHalvingPeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetInterestGapHalvingPeriod), arg0)
}

// GetInterestTokenIDs mocks base method.
func (m *MockEnterpriseBlockchain) GetInterestTokenIDs(arg0, arg1 common.Address) ([]*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterestTokenIDs", arg0, arg1)
	ret0, _ := ret[0].([]*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterestTokenIDs indicates an expected call of GetInterestTokenIDs.
func (mr *MockEnterpriseBlockchainMockRecorder) GetInterestTokenIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterestTokenIDs", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetInterestTokenIDs), arg0, arg1)
}

// GetLiquidityInfo mocks base method.
func (m *MockEnterpriseBlockchain) GetLiquidityInfo(arg0 common.Address, arg1 *big.Int) (eip155.LiquidityInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiquidityInfo", arg0, arg1)
	ret0, _ := ret[0].(eip155.LiquidityInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLiquidityInfo indicates an expected call of GetLiquidityInfo.
func (mr *MockEnterpriseBlockchainMockRecorder) GetLiquidityInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiquidityInfo", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetLiquidityInfo), arg0, arg1)
}

// GetLiquidityTokenEnterpriseAllowance mocks base method.
func (m *MockEnterpriseBlockchain) GetLiquidityTokenEnterpriseAllowance(arg0, arg1 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiquidityTokenEnterpriseAllowance", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLiquidityTokenEnterpriseAllowance indicates an expected call of GetLiquidityTokenEnterpriseAllowance.
func (mr *MockEnterpriseBlockchainMockRecorder) GetLiquidityTokenEnterpriseAllowance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiquidityTokenEnterpriseAllowance", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetLiquidityTokenEnterpriseAllowance), arg0, arg1)
}

// GetLiquidityTokenServiceAllowance mocks base method.
func (m *MockEnterpriseBlockchain) GetLiquidityTokenServiceAllowance(arg0, arg1 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiquidityTokenServiceAllowance", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLiquidityTokenServiceAllowance indicates an expected call of GetLiquidityTokenServiceAllowance.
func (mr *MockEnterpriseBlockchainMockRecorder) GetLiquidityTokenServiceAllowance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiquidityTokenServiceAllowance", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetLiquidityTokenServiceAllowance), arg0, arg1)
}

// GetLoanInfo mocks base method.
func (m *MockEnterpriseBlockchain) GetLoanInfo(arg0 common.Address, arg1 *big.Int) (eip155.LoanInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanInfo", arg0, arg1)
	ret0, _ := ret[0].(eip155.LoanInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanInfo indicates an expected call of GetLoanInfo.
func (mr *MockEnterpriseBlockchainMockRecorder) GetLoanInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanInfo", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetLoanInfo), arg0, arg1)
}

// GetMaxLoanDuration mocks base method.
func (m *MockEnterpriseBlockchain) GetMaxLoanDuration(arg0 common.Address) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxLoanDuration", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxLoanDuration indicates an expected call of GetMaxLoanDuration.
func (mr *MockEnterpriseBlockchainMockRecorder) GetMaxLoanDuration(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxLoanDuration", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetMaxLoanDuration), arg0)
}

// GetMinGCFee mocks base method.
func (m *MockEnterpriseBlockchain) GetMinGCFee(arg0 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinGCFee", arg0)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinGCFee indicates an expected call of GetMinGCFee.
func (mr *MockEnterpriseBlockchainMockRecorder) GetMinGCFee(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinGCFee", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetMinGCFee), arg0)
}

// GetMinLoanDuration mocks base method.
func (m *MockEnterpriseBlockchain) GetMinLoanDuration(arg0 common.Address) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinLoanDuration", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinLoanDuration indicates an expected call of GetMinLoanDuration.
func (mr *MockEnterpriseBlockchainMockRecorder) GetMinLoanDuration(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinLoanDuration", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetMinLoanDuration), arg0)
}

// GetPowerTokenAvailableBalance mocks base method.
func (m *MockEnterpriseBlockchain) GetPowerTokenAvailableBalance(arg0, arg1 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerTokenAvailableBalance", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerTokenAvailableBalance indicates an expected call of GetPowerTokenAvailableBalance.
func (mr *MockEnterpriseBlockchainMockRecorder) GetPowerTokenAvailableBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerTokenAvailableBalance", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetPowerTokenAvailableBalance), arg0, arg1)
}

// GetPowerTokenBalance mocks base method.
func (m *MockEnterpriseBlockchain) GetPowerTokenBalance(arg0, arg1 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerTokenBalance", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerTokenBalance indicates an expected call of GetPowerTokenBalance.
func (mr *MockEnterpriseBlockchainMockRecorder) GetPowerTokenBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerTokenBalance", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetPowerTokenBalance), arg0, arg1)
}

// GetProxyAdminAddress mocks base method.
func (m *MockEnterpriseBlockchain) GetProxyAdminAddress(arg0 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyAdminAddress", arg0)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyAdminAddress indicates an expected call of GetProxyAdminAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) GetProxyAdminAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyAdminAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetProxyAdminAddress), arg0)
}

// GetReserve mocks base method.
func (m *MockEnterpriseBlockchain) GetReserve(arg0 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReserve", arg0)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReserve indicates an expected call of GetReserve.
func (mr *MockEnterpriseBlockchainMockRecorder) GetReserve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReserve", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetReserve), arg0)
}

// GetServiceFeePercent mocks base method.
func (m *MockEnterpriseBlockchain) GetServiceFeePercent(arg0 common.Address) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceFeePercent", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceFeePercent indicates an expected call of GetServiceFeePercent.
func (mr *MockEnterpriseBlockchainMockRecorder) GetServiceFeePercent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceFeePercent", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetServiceFeePercent), arg0)
}

// GetServiceIndex mocks base method.
func (m *MockEnterpriseBlockchain) GetServiceIndex(arg0 common.Address) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceIndex", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceIndex indicates an expected call of GetServiceIndex.
func (mr *MockEnterpriseBlockchainMockRecorder) GetServiceIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceIndex", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetServiceIndex), arg0)
}

// GetServiceInfo mocks base method.
func (m *MockEnterpriseBlockchain) GetServiceInfo(arg0 common.Address) (eip155.ServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInfo", arg0)
	ret0, _ := ret[0].(eip155.ServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
func (mr *MockEnterpriseBlockchainMockRecorder) GetServiceInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetServiceInfo), arg0)
}

// GetServices mocks base method.
func (m *MockEnterpriseBlockchain) GetServices(arg0 common.Address) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", arg0)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockEnterpriseBlockchainMockRecorder) GetServices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetServices), arg0)
}

// GetUsedReserve mocks base method.
func (m *MockEnterpriseBlockchain) GetUsedReserve(arg0 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsedReserve", arg0)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsedReserve indicates an expected call of GetUsedReserve.
func (mr *MockEnterpriseBlockchainMockRecorder) GetUsedReserve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsedReserve", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).GetUsedReserve), arg0)
}

// IncreaseLiquidity mocks base method.
func (m *MockEnterpriseBlockchain) IncreaseLiquidity(arg0 common.Address, arg1, arg2 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseLiquidity", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseLiquidity indicates an expected call of IncreaseLiquidity.
func (mr *MockEnterpriseBlockchainMockRecorder) IncreaseLiquidity(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseLiquidity", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).IncreaseLiquidity), arg0, arg1, arg2)
}

// IsRegisteredService mocks base method.
func (m *MockEnterpriseBlockchain) IsRegisteredService(arg0, arg1 common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRegisteredService", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRegisteredService indicates an expected call of IsRegisteredService.
func (mr *MockEnterpriseBlockchainMockRecorder) IsRegisteredService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRegisteredService", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).IsRegisteredService), arg0, arg1)
}

// RemoveLiquidity mocks base method.
func (m *MockEnterpriseBlockchain) RemoveLiquidity(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLiquidity", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLiquidity indicates an expected call of RemoveLiquidity.
func (mr *MockEnterpriseBlockchainMockRecorder) RemoveLiquidity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLiquidity", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).RemoveLiquidity), arg0, arg1)
}

// ReturnLoan mocks base method.
func (m *MockEnterpriseBlockchain) ReturnLoan(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnLoan", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturnLoan indicates an expected call of ReturnLoan.
func (mr *MockEnterpriseBlockchainMockRecorder) ReturnLoan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnLoan", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).ReturnLoan), arg0, arg1)
}

// SetBaseRate mocks base method.
func (m *MockEnterpriseBlockchain) SetBaseRate(arg0, arg1 common.Address, arg2, arg3 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBaseRate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBaseRate indicates an expected call of SetBaseRate.
func (mr *MockEnterpriseBlockchainMockRecorder) SetBaseRate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBaseRate", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetBaseRate), arg0, arg1, arg2, arg3)
}

// SetBaseUri mocks base method.
func (m *MockEnterpriseBlockchain) SetBaseUri(arg0 common.Address, arg1 string) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBaseUri", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBaseUri indicates an expected call of SetBaseUri.
func (mr *MockEnterpriseBlockchainMockRecorder) SetBaseUri(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBaseUri", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetBaseUri), arg0, arg1)
}

// SetBondingCurve mocks base method.
func (m *MockEnterpriseBlockchain) SetBondingCurve(arg0 common.Address, arg1, arg2 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBondingCurve", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBondingCurve indicates an expected call of SetBondingCurve.
func (mr *MockEnterpriseBlockchainMockRecorder) SetBondingCurve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBondingCurve", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetBondingCurve), arg0, arg1, arg2)
}

// SetBorrowerLoanReturnGracePeriod mocks base method.
func (m *MockEnterpriseBlockchain) SetBorrowerLoanReturnGracePeriod(arg0 common.Address, arg1 uint32) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBorrowerLoanReturnGracePeriod", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBorrowerLoanReturnGracePeriod indicates an expected call of SetBorrowerLoanReturnGracePeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) SetBorrowerLoanReturnGracePeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBorrowerLoanReturnGracePeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetBorrowerLoanReturnGracePeriod), arg0, arg1)
}

// SetConverterAddress mocks base method.
func (m *MockEnterpriseBlockchain) SetConverterAddress(arg0, arg1 common.Address) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConverterAddress", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetConverterAddress indicates an expected call of SetConverterAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) SetConverterAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConverterAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetConverterAddress), arg0, arg1)
}

// SetEnterpriseCollectorAddress mocks base method.
func (m *MockEnterpriseBlockchain) SetEnterpriseCollectorAddress(arg0, arg1 common.Address) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnterpriseCollectorAddress", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnterpriseCollectorAddress indicates an expected call of SetEnterpriseCollectorAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) SetEnterpriseCollectorAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnterpriseCollectorAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetEnterpriseCollectorAddress), arg0, arg1)
}

// SetEnterpriseLoanCollectGracePeriod mocks base method.
func (m *MockEnterpriseBlockchain) SetEnterpriseLoanCollectGracePeriod(arg0 common.Address, arg1 uint32) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnterpriseLoanCollectGracePeriod", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnterpriseLoanCollectGracePeriod indicates an expected call of SetEnterpriseLoanCollectGracePeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) SetEnterpriseLoanCollectGracePeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnterpriseLoanCollectGracePeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetEnterpriseLoanCollectGracePeriod), arg0, arg1)
}

// SetEnterpriseVaultAddress mocks base method.
func (m *MockEnterpriseBlockchain) SetEnterpriseVaultAddress(arg0, arg1 common.Address) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnterpriseVaultAddress", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnterpriseVaultAddress indicates an expected call of SetEnterpriseVaultAddress.
func (mr *MockEnterpriseBlockchainMockRecorder) SetEnterpriseVaultAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnterpriseVaultAddress", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetEnterpriseVaultAddress), arg0, arg1)
}

// SetGCFeePercent mocks base method.
func (m *MockEnterpriseBlockchain) SetGCFeePercent(arg0 common.Address, arg1 uint16) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGCFeePercent", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetGCFeePercent indicates an expected call of SetGCFeePercent.
func (mr *MockEnterpriseBlockchainMockRecorder) SetGCFeePercent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGCFeePercent", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetGCFeePercent), arg0, arg1)
}

// SetInterestGapHalvingPeriod mocks base method.
func (m *MockEnterpriseBlockchain) SetInterestGapHalvingPeriod(arg0 common.Address, arg1 uint32) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInterestGapHalvingPeriod", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInterestGapHalvingPeriod indicates an expected call of SetInterestGapHalvingPeriod.
func (mr *MockEnterpriseBlockchainMockRecorder) SetInterestGapHalvingPeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInterestGapHalvingPeriod", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetInterestGapHalvingPeriod), arg0, arg1)
}

// SetLoanDurationLimits mocks base method.
func (m *MockEnterpriseBlockchain) SetLoanDurationLimits(arg0 common.Address, arg1, arg2 uint32) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoanDurationLimits", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLoanDurationLimits indicates an expected call of SetLoanDurationLimits.
func (mr *MockEnterpriseBlockchainMockRecorder) SetLoanDurationLimits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoanDurationLimits", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetLoanDurationLimits), arg0, arg1, arg2)
}

// SetServiceFeePercent mocks base method.
func (m *MockEnterpriseBlockchain) SetServiceFeePercent(arg0 common.Address, arg1 uint16) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetServiceFeePercent", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetServiceFeePercent indicates an expected call of SetServiceFeePercent.
func (mr *MockEnterpriseBlockchainMockRecorder) SetServiceFeePercent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServiceFeePercent", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).SetServiceFeePercent), arg0, arg1)
}

// Unwrap mocks base method.
func (m *MockEnterpriseBlockchain) Unwrap(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unwrap", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unwrap indicates an expected call of Unwrap.
func (mr *MockEnterpriseBlockchainMockRecorder) Unwrap(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unwrap", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).Unwrap), arg0, arg1)
}

// WithdrawInterest mocks base method.
func (m *MockEnterpriseBlockchain) WithdrawInterest(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawInterest", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithdrawInterest indicates an expected call of WithdrawInterest.
func (mr *MockEnterpriseBlockchainMockRecorder) WithdrawInterest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawInterest", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).WithdrawInterest), arg0, arg1)
}

// Wrap mocks base method.
func (m *MockEnterpriseBlockchain) Wrap(arg0 common.Address, arg1 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", arg0, arg1)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wrap indicates an expected call of Wrap.
func (mr *MockEnterpriseBlockchainMockRecorder) Wrap(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).Wrap), arg0, arg1)
}

// WrapTo mocks base method.
func (m *MockEnterpriseBlockchain) WrapTo(arg0, arg1 common.Address, arg2 *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WrapTo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WrapTo indicates an expected call of WrapTo.
func (mr *MockEnterpriseBlockchainMockRecorder) WrapTo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WrapTo", reflect.TypeOf((*MockEnterpriseBlockchain)(nil).WrapTo), arg0, arg1, arg2)
}
