// Code generated by "stringer -type=IQContractName"; DO NOT EDIT.

package discovery

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BorrowToken-0]
	_ = x[DefaultConverter-1]
	_ = x[Enterprise-2]
	_ = x[EnterpriseFactory-3]
	_ = x[InterestToken-4]
	_ = x[PowerToken-5]
}

const _IQContractName_name = "BorrowTokenDefaultConverterEnterpriseEnterpriseFactoryInterestTokenPowerToken"

var _IQContractName_index = [...]uint8{0, 11, 27, 37, 54, 67, 77}

func (i IQContractName) String() string {
	if i < 0 || i >= IQContractName(len(_IQContractName_index)-1) {
		return "IQContractName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IQContractName_name[_IQContractName_index[i]:_IQContractName_index[i+1]]
}
